name: Publish
on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          # https://github.com/actions/node-versions/releases
          node-version: 24.21.0
          registry-url: https://registry.npmjs.org/

      # The pnpm version is read from the "packageManager" field in package.json
      - uses: pnpm/action-setup@v6.1.0

      - run: pnpm install

      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}